//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.27 at 10:12:17 AM ALMT 
//


package kz.gov.services.gbd.unifl;

import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kz.gov.services.gbd.unifl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SendMessageRequest_QNAME = new QName("http://smartbridge.b10.kz", "sendMessageRequest");
    private final static QName _SendMessageResponse_QNAME = new QName("http://smartbridge.b10.kz", "sendMessageResponse");
    private final static QName _AddressTypeChangeDate_QNAME = new QName("", "changeDate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kz.gov.services.gbd.unifl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Participant }
     * 
     */
    public Participant createParticipant() {
        return new Participant();
    }

    /**
     * Create an instance of {@link MessageResult }
     * 
     */
    public MessageResult createMessageResult() {
        return new MessageResult();
    }

    /**
     * Create an instance of {@link Gender }
     * 
     */
    public Gender createGender() {
        return new Gender();
    }

    /**
     * Create an instance of {@link Nationality }
     * 
     */
    public Nationality createNationality() {
        return new Nationality();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link PersonStatus }
     * 
     */
    public PersonStatus createPersonStatus() {
        return new PersonStatus();
    }

    /**
     * Create an instance of {@link ImprisoneStatus }
     * 
     */
    public ImprisoneStatus createImprisoneStatus() {
        return new ImprisoneStatus();
    }

    /**
     * Create an instance of {@link District }
     * 
     */
    public District createDistrict() {
        return new District();
    }

    /**
     * Create an instance of {@link Region }
     * 
     */
    public Region createRegion() {
        return new Region();
    }

    /**
     * Create an instance of {@link AddressStatus }
     * 
     */
    public AddressStatus createAddressStatus() {
        return new AddressStatus();
    }

    /**
     * Create an instance of {@link AddressInvalidity }
     * 
     */
    public AddressInvalidity createAddressInvalidity() {
        return new AddressInvalidity();
    }

    /**
     * Create an instance of {@link CapableStatus }
     * 
     */
    public CapableStatus createCapableStatus() {
        return new CapableStatus();
    }

    /**
     * Create an instance of {@link Court }
     * 
     */
    public Court createCourt() {
        return new Court();
    }

    /**
     * Create an instance of {@link GpTerritorial }
     * 
     */
    public GpTerritorial createGpTerritorial() {
        return new GpTerritorial();
    }

    /**
     * Create an instance of {@link ExcludeReason }
     * 
     */
    public ExcludeReason createExcludeReason() {
        return new ExcludeReason();
    }

    /**
     * Create an instance of {@link RepatriationStatus }
     * 
     */
    public RepatriationStatus createRepatriationStatus() {
        return new RepatriationStatus();
    }

    /**
     * Create an instance of {@link RepatriationOrg }
     * 
     */
    public RepatriationOrg createRepatriationOrg() {
        return new RepatriationOrg();
    }

    /**
     * Create an instance of {@link RepatriationReason }
     * 
     */
    public RepatriationReason createRepatriationReason() {
        return new RepatriationReason();
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link DocumentOrganization }
     * 
     */
    public DocumentOrganization createDocumentOrganization() {
        return new DocumentOrganization();
    }

    /**
     * Create an instance of {@link DocumentInvalidity }
     * 
     */
    public DocumentInvalidity createDocumentInvalidity() {
        return new DocumentInvalidity();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link PersonImprisoneStatus }
     * 
     */
    public PersonImprisoneStatus createPersonImprisoneStatus() {
        return new PersonImprisoneStatus();
    }

    /**
     * Create an instance of {@link Certificate }
     * 
     */
    public Certificate createCertificate() {
        return new Certificate();
    }

    /**
     * Create an instance of {@link BirthPlace }
     * 
     */
    public BirthPlace createBirthPlace() {
        return new BirthPlace();
    }

    /**
     * Create an instance of {@link ForeignData }
     * 
     */
    public ForeignData createForeignData() {
        return new ForeignData();
    }

    /**
     * Create an instance of {@link RegAddress }
     * 
     */
    public RegAddress createRegAddress() {
        return new RegAddress();
    }

    /**
     * Create an instance of {@link PersonCapableStatus }
     * 
     */
    public PersonCapableStatus createPersonCapableStatus() {
        return new PersonCapableStatus();
    }

    /**
     * Create an instance of {@link MissingStatus }
     * 
     */
    public MissingStatus createMissingStatus() {
        return new MissingStatus();
    }

    /**
     * Create an instance of {@link DisappearStatus }
     * 
     */
    public DisappearStatus createDisappearStatus() {
        return new DisappearStatus();
    }

    /**
     * Create an instance of {@link PersonExcludeStatus }
     * 
     */
    public PersonExcludeStatus createPersonExcludeStatus() {
        return new PersonExcludeStatus();
    }

    /**
     * Create an instance of {@link PersonRepatriationStatus }
     * 
     */
    public PersonRepatriationStatus createPersonRepatriationStatus() {
        return new PersonRepatriationStatus();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Person.Documents }
     * 
     */
    public Person.Documents createPersonDocuments() {
        return new Person.Documents();
    }

    /**
     * Create an instance of {@link Person.Addresses }
     * 
     */
    public Person.Addresses createPersonAddresses() {
        return new Person.Addresses();
    }

    /**
     * Create an instance of {@link Response.Persons }
     * 
     */
    public Response.Persons createResponsePersons() {
        return new Response.Persons();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Request }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Request }{@code >}
     */
    @XmlElementDecl(namespace = "http://smartbridge.b10.kz", name = "sendMessageRequest")
    public JAXBElement<Request> createSendMessageRequest(Request value) {
        return new JAXBElement<Request>(_SendMessageRequest_QNAME, Request.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     */
    @XmlElementDecl(namespace = "http://smartbridge.b10.kz", name = "sendMessageResponse")
    public JAXBElement<Response> createSendMessageResponse(Response value) {
        return new JAXBElement<Response>(_SendMessageResponse_QNAME, Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = AddressType.class)
    public JAXBElement<XMLGregorianCalendar> createAddressTypeChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, AddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = DocumentInvalidity.class)
    public JAXBElement<XMLGregorianCalendar> createDocumentInvalidityChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, DocumentInvalidity.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = DocumentOrganization.class)
    public JAXBElement<XMLGregorianCalendar> createDocumentOrganizationChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, DocumentOrganization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = DocumentType.class)
    public JAXBElement<XMLGregorianCalendar> createDocumentTypeChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, DocumentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = RepatriationReason.class)
    public JAXBElement<XMLGregorianCalendar> createRepatriationReasonChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, RepatriationReason.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = RepatriationOrg.class)
    public JAXBElement<XMLGregorianCalendar> createRepatriationOrgChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, RepatriationOrg.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = RepatriationStatus.class)
    public JAXBElement<XMLGregorianCalendar> createRepatriationStatusChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, RepatriationStatus.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = ExcludeReason.class)
    public JAXBElement<XMLGregorianCalendar> createExcludeReasonChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, ExcludeReason.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = GpTerritorial.class)
    public JAXBElement<XMLGregorianCalendar> createGpTerritorialChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, GpTerritorial.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = Court.class)
    public JAXBElement<XMLGregorianCalendar> createCourtChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, Court.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = CapableStatus.class)
    public JAXBElement<XMLGregorianCalendar> createCapableStatusChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, CapableStatus.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = AddressInvalidity.class)
    public JAXBElement<XMLGregorianCalendar> createAddressInvalidityChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, AddressInvalidity.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = AddressStatus.class)
    public JAXBElement<XMLGregorianCalendar> createAddressStatusChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, AddressStatus.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = Region.class)
    public JAXBElement<XMLGregorianCalendar> createRegionChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, Region.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = District.class)
    public JAXBElement<XMLGregorianCalendar> createDistrictChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, District.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = ImprisoneStatus.class)
    public JAXBElement<XMLGregorianCalendar> createImprisoneStatusChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, ImprisoneStatus.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = PersonStatus.class)
    public JAXBElement<XMLGregorianCalendar> createPersonStatusChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, PersonStatus.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = Country.class)
    public JAXBElement<XMLGregorianCalendar> createCountryChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, Country.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = Nationality.class)
    public JAXBElement<XMLGregorianCalendar> createNationalityChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, Nationality.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = Gender.class)
    public JAXBElement<XMLGregorianCalendar> createGenderChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, Gender.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = MessageResult.class)
    public JAXBElement<XMLGregorianCalendar> createMessageResultChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, MessageResult.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "changeDate", scope = Participant.class)
    public JAXBElement<XMLGregorianCalendar> createParticipantChangeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressTypeChangeDate_QNAME, XMLGregorianCalendar.class, Participant.class, value);
    }

}
