//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.22 at 02:59:23 PM ALMT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://dictionaries.persistence.interactive.nat")
package kz.gov.services.gbd.unifl;
