//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.22 at 02:59:23 PM ALMT 
//


package kz.gov.services.gbd.unifl;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Статус оралмана
 * 
 * <p>Java class for personRepatriationStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="personRepatriationStatus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="repatriationStatus" type="{http://dictionaries.persistence.interactive.nat}repatriationStatus" minOccurs="0"/&gt;
 *         &lt;element name="repatriationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="repatriationEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="repatriationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="repatriationOrg" type="{http://dictionaries.persistence.interactive.nat}repatriationOrg" minOccurs="0"/&gt;
 *         &lt;element name="repatriationReason" type="{http://dictionaries.persistence.interactive.nat}repatriationReason" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "personRepatriationStatus", namespace = "http://person.persistence.interactive.nat", propOrder = {
    "repatriationStatus",
    "repatriationDate",
    "repatriationEndDate",
    "repatriationNumber",
    "repatriationOrg",
    "repatriationReason"
})
public class PersonRepatriationStatus {

    protected RepatriationStatus repatriationStatus;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar repatriationDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar repatriationEndDate;
    protected String repatriationNumber;
    protected RepatriationOrg repatriationOrg;
    protected RepatriationReason repatriationReason;

    /**
     * Gets the value of the repatriationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RepatriationStatus }
     *     
     */
    public RepatriationStatus getRepatriationStatus() {
        return repatriationStatus;
    }

    /**
     * Sets the value of the repatriationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepatriationStatus }
     *     
     */
    public void setRepatriationStatus(RepatriationStatus value) {
        this.repatriationStatus = value;
    }

    /**
     * Gets the value of the repatriationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRepatriationDate() {
        return repatriationDate;
    }

    /**
     * Sets the value of the repatriationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRepatriationDate(XMLGregorianCalendar value) {
        this.repatriationDate = value;
    }

    /**
     * Gets the value of the repatriationEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRepatriationEndDate() {
        return repatriationEndDate;
    }

    /**
     * Sets the value of the repatriationEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRepatriationEndDate(XMLGregorianCalendar value) {
        this.repatriationEndDate = value;
    }

    /**
     * Gets the value of the repatriationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepatriationNumber() {
        return repatriationNumber;
    }

    /**
     * Sets the value of the repatriationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepatriationNumber(String value) {
        this.repatriationNumber = value;
    }

    /**
     * Gets the value of the repatriationOrg property.
     * 
     * @return
     *     possible object is
     *     {@link RepatriationOrg }
     *     
     */
    public RepatriationOrg getRepatriationOrg() {
        return repatriationOrg;
    }

    /**
     * Sets the value of the repatriationOrg property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepatriationOrg }
     *     
     */
    public void setRepatriationOrg(RepatriationOrg value) {
        this.repatriationOrg = value;
    }

    /**
     * Gets the value of the repatriationReason property.
     * 
     * @return
     *     possible object is
     *     {@link RepatriationReason }
     *     
     */
    public RepatriationReason getRepatriationReason() {
        return repatriationReason;
    }

    /**
     * Sets the value of the repatriationReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepatriationReason }
     *     
     */
    public void setRepatriationReason(RepatriationReason value) {
        this.repatriationReason = value;
    }

}
