//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.27 at 10:12:17 AM ALMT 
//


package kz.gov.services.gbd.unifl;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Сведения об осужденном
 * 
 * <p>Java class for PersonImprisoneStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonImprisoneStatus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="imprisonedStatus" type="{http://dictionaries.persistence.interactive.nat}ImprisoneStatus"/&gt;
 *         &lt;element name="imprisonedBeginDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="imprisonedEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonImprisoneStatus", namespace = "http://person.persistence.interactive.nat", propOrder = {
    "imprisonedStatus",
    "imprisonedBeginDate",
    "imprisonedEndDate"
})
public class PersonImprisoneStatus {

    @XmlElement(required = true)
    protected ImprisoneStatus imprisonedStatus;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar imprisonedBeginDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar imprisonedEndDate;

    /**
     * Gets the value of the imprisonedStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ImprisoneStatus }
     *     
     */
    public ImprisoneStatus getImprisonedStatus() {
        return imprisonedStatus;
    }

    /**
     * Sets the value of the imprisonedStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImprisoneStatus }
     *     
     */
    public void setImprisonedStatus(ImprisoneStatus value) {
        this.imprisonedStatus = value;
    }

    /**
     * Gets the value of the imprisonedBeginDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getImprisonedBeginDate() {
        return imprisonedBeginDate;
    }

    /**
     * Sets the value of the imprisonedBeginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setImprisonedBeginDate(XMLGregorianCalendar value) {
        this.imprisonedBeginDate = value;
    }

    /**
     * Gets the value of the imprisonedEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getImprisonedEndDate() {
        return imprisonedEndDate;
    }

    /**
     * Sets the value of the imprisonedEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setImprisonedEndDate(XMLGregorianCalendar value) {
        this.imprisonedEndDate = value;
    }

}
