//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.22 at 02:59:23 PM ALMT 
//


package kz.gov.services.gbd.unifl;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Признак исключения/условного исключения ИИН из Национального реестра
 * 
 * <p>Java class for PersonExcludeStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonExcludeStatus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="excludeReason" type="{http://dictionaries.persistence.interactive.nat}ExcludeReason"/&gt;
 *         &lt;element name="excludeReasonDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="excludeDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="excludeParticipant" type="{http://dictionaries.persistence.interactive.nat}Participant" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonExcludeStatus", namespace = "http://person.persistence.interactive.nat", propOrder = {
    "excludeReason",
    "excludeReasonDate",
    "excludeDate",
    "excludeParticipant"
})
public class PersonExcludeStatus {

    @XmlElement(required = true)
    protected ExcludeReason excludeReason;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar excludeReasonDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar excludeDate;
    protected Participant excludeParticipant;

    /**
     * Gets the value of the excludeReason property.
     * 
     * @return
     *     possible object is
     *     {@link ExcludeReason }
     *     
     */
    public ExcludeReason getExcludeReason() {
        return excludeReason;
    }

    /**
     * Sets the value of the excludeReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExcludeReason }
     *     
     */
    public void setExcludeReason(ExcludeReason value) {
        this.excludeReason = value;
    }

    /**
     * Gets the value of the excludeReasonDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExcludeReasonDate() {
        return excludeReasonDate;
    }

    /**
     * Sets the value of the excludeReasonDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExcludeReasonDate(XMLGregorianCalendar value) {
        this.excludeReasonDate = value;
    }

    /**
     * Gets the value of the excludeDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExcludeDate() {
        return excludeDate;
    }

    /**
     * Sets the value of the excludeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExcludeDate(XMLGregorianCalendar value) {
        this.excludeDate = value;
    }

    /**
     * Gets the value of the excludeParticipant property.
     * 
     * @return
     *     possible object is
     *     {@link Participant }
     *     
     */
    public Participant getExcludeParticipant() {
        return excludeParticipant;
    }

    /**
     * Sets the value of the excludeParticipant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Participant }
     *     
     */
    public void setExcludeParticipant(Participant value) {
        this.excludeParticipant = value;
    }

}
